name: ThirdFirstPlugin
version: '${project.version}'
main: pl.accureter.thirdfirstplugin.ThirdFirstPlugin
api-version: 1.19
author: _Accureter
description: Plugin made with Kody Simpson plugin tutorial series "Spigot Plugin Development"
website: https://www.accureter.pl
commands:
  die:
    description: Zabijesz się (SERIO)
    usage: /<command>
  god:
    description: Zostań nieśmiertelny
    usage: /<command>
    aliases:
      - accumode
      - bozia
  feed:
    description: Nakarm się
    usage: /<command>
  messageFromConfig:
    description: Wypisz z configu
    usage: /<command>
  config:
    description: Wypisz z configu
    usage: /<command>
  repeat:
    description: Powtórzy co powiesz wtf
    usage: /<command> <args>
  fart:
    description: Walisz bona na łeb
    usage: /<command> <player>
  setspawn:
    description: Ustawia spawnpoint
    usage: /<command>
  spawn:
    description: Teleportuje do spawnu
    usage: /<command>
  menu:
    description: Otwiera menu
    usage: /<command>
  fly:
    description: Latanie
    usage: /<command>
  givetpbow:
    description: Gives teleport bow!
  armorstand:
    description: Spawns an Armor Stand!
  gui:
    description: Opens a GUI
  asgui:
    description: Create an armor stand
  hologram:
    description: Create a hologram
  customConfig:
    description: Sends a message from custom config
  customConfigReload:
    description: Reloads custom config
  sign:
    description: Create sign in player location
  bangui:
    description: Open ban GUI
  rtp:
    description: Teleports in random location
  vanish:
    description: Vanishes you!