name: ThirdFirstPlugin
version: '${project.version}'
main: pl.accureter.thirdfirstplugin.ThirdFirstPlugin
api-version: 1.19
commands:
  die:
    description: Zabijesz się (SERIO)
    usage: /<command>
  god:
    description: Zostań nieśmiertelny
    usage: /<command>
    aliases:
      - accumode
      - bozia
  feed:
    description: Nakarm się
    usage: /<command>
  messageFromConfig:
    description: Wypisz z configu
    usage: /<command>
  config:
    description: Wypisz z configu
    usage: /<command>
  repeat:
    description: Powtórzy co powiesz wtf
    usage: /<command> <args>
  fart:
    description: Walisz bona na łeb
    usage: /<command> <player>
  setspawn:
    description: Ustawia spawnpoint
    usage: /<command>
  spawn:
    description: Teleportuje do spawnu
    usage: /<command>
  menu:
    description: Otwiera menu
    usage: /<command>